# Generated by Django 4.0.2 on 2022-02-26 18:38

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import posting.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('course_introduction', models.TextField()),
                ('instructor_introduction', models.CharField(max_length=200)),
                ('instructor_name', models.CharField(max_length=10)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=posting.models.upload_to)),
                ('job', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.IntegerField(blank=True, default=0)),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('contents', models.TextField(null=True)),
                ('youtube_id', models.CharField(max_length=255, null=True)),
                ('meeting_id', models.CharField(max_length=20, null=True)),
                ('survey_url', models.CharField(max_length=200, null=True)),
                ('category', models.CharField(choices=[('LECTURE', '동영상 강의'), ('WATCH', '동영상 시청'), ('ANALYSIS', '팀 사례분석'), ('DEBRIEFING', '팀 디브리핑'), ('PROJECT', '팀 프로젝트'), ('DOWNLOAD', '학습 자료실'), ('BOARD', '열린 게시판'), ('QNA', 'Q&A'), ('SURVEY', '설문하기')], max_length=20)),
                ('files', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('download', models.IntegerField(default=0)),
                ('secret', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('posting', models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posting.posting')),
            ],
        ),
    ]
