# Generated by Django 4.0.2 on 2022-02-27 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwatchvideo',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postingfiles',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posting_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postingfiles',
            name='posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting_files', to='posting.posting'),
        ),
        migrations.AddField(
            model_name='posting',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='posting',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posting.posting'),
        ),
        migrations.AlterUniqueTogether(
            name='userwatchvideo',
            unique_together={('posting', 'user')},
        ),
    ]
