# Generated by Django 4.0.2 on 2022-02-26 18:31

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0004_rename_lecture_posting_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='posting',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posting.posting'),
        ),
        migrations.AddField(
            model_name='posting',
            name='category',
            field=models.CharField(choices=[('LECTURE', '동영상 강의'), ('WATCH', '동영상 시청'), ('ANALYSIS', '팀 사례분석'), ('DEBRIEFING', '팀 디브리핑'), ('PROJECT', '팀 프로젝트'), ('DOWNLOAD', '학습 자료실'), ('BOARD', '열린 게시판'), ('QNA', 'Q&A'), ('SURVEY', '설문하기')], default='LECTURE', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posting',
            name='download',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posting',
            name='files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='posting',
            name='meeting_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='posting',
            name='secret',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posting',
            name='survey_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='posting',
            name='contents',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='posting',
            name='youtube_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
